spring:
  datasource:
    username: root
    password: 57630309
    url: jdbc:mysql://127.0.0.1:3306/nocv?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  server:
    port: 8080  # 端口号
  thymeleaf:
    prefix:
      classpath: /templates/**
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    main:
       allow-circular-references: true

#shiro的配置
shiro:
  anon-urls:
    - /toLogin*
    - /login.html*
    - /login/login
    - /login/getCode
    - /css/**
    - /echarts/**
    - /images/**
    - /layui/**
    - /layui_ext/**
    - /js/**
  login-url: /index2.html
  log-out-url: /login/loginout*
  authc-ulrs:
    - /**


